<?php

$messages['f2b_banned'] = 'Liiga palju ebaõnnestunud sisselogimise katseid. Palun proovige hiljem uuesti.';
$messages['f2b_banned_for'] = 'Liiga palju ebaõnnestunud sisselogimise katseid. Palun proovige uuesti :ban_time minuti pärast.';
$messages['f2b_blacklisted'] = 'Teie võrk on mustas nimekirjas. Palun võtke ühendust klienditoega.';
$messages['f2b_invalid_chars'] = 'Kasutajanimes on sobimatud tähemärgid.';

?>
