<?php

$messages['f2b_banned'] = 'Liian monta epäonnistunutta kirjautumisyritystä. Yritä uudelleen myöhemmin.';
$messages['f2b_banned_for'] = 'Liian monta epäonnistunutta kirjautumisyritystä. Yritä uudelleen :ban_time minuutin kuluttua.';
$messages['f2b_blacklisted'] = 'Verkkosi on mustalla listalla. Ota yhteyttä tukeen.';
$messages['f2b_invalid_chars'] = 'Käyttäjänimessä on virheellisiä merkkejä.';

?>
