<?php

$messages['f2b_banned'] = 'Túl sok sikertelen bejelentkezési kísérlet. Kérlek, próbáld újra később.';
$messages['f2b_banned_for'] = 'Túl sok sikertelen bejelentkezési kísérlet. Kérjük, próbálja újra :ban_time perc múlva.';
$messages['f2b_blacklisted'] = 'A hálózatod tiltólistán van. Kérjük, vedd fel a kapcsolatot az ügyfélszolgálattal.';
$messages['f2b_invalid_chars'] = 'Érvénytelen karakterek a felhasználónévben.';

?>
